/**
 * types/index.ts
 * ----------------------------------------------------------------------------
 * Central type definitions for the Trading Journal app.
 *
 * Keeping every shared type in one place makes it easy to see the shape of
 * the app's data model at a glance, and avoids circular imports between
 * components/context/utils.
 * ----------------------------------------------------------------------------
 */

/** A trade is either a "long" (bought expecting price to rise) or a
 *  "short" (sold/borrowed expecting price to fall) position. */
export type PositionType = 'long' | 'short';

/** Lifecycle state of a trade. "open" trades have no exit price yet. */
export type TradeStatus = 'open' | 'closed';

/**
 * Core Trade record.
 *
 * Note on RR (Risk:Reward): to auto-calculate RR we need a planned
 * `stopLoss` (defines risk) and, ideally, a `takeProfit` (defines the
 * planned reward). These two fields are additions on top of the original
 * "entry price / closing price" requirement, because RR cannot be derived
 * from entry & exit price alone (exit price is what actually happened,
 * not what was planned). See utils/calculations.ts for the formulas.
 */
export interface Trade {
  /** Unique identifier (generated client-side with crypto.randomUUID). */
  id: string;
  /** Owner of this trade — ties the record to a logged-in user. */
  userId: string;

  /** Instrument/ticker being traded, e.g. "EURUSD", "AAPL", "BTCUSDT". */
  symbol: string;
  /** Long or short. */
  positionType: PositionType;
  /** Number of units/contracts traded. Must be > 0. */
  quantity: number;
  /** Leverage multiplier for this futures position, e.g. 10 for "10x".
   *  Use 1 for an unleveraged (1x) position. Must be >= 1. Leverage changes
   *  how much margin a position ties up (and therefore its PnL% / ROE),
   *  but does NOT change the dollar PnL or the R-multiple — see the note
   *  in utils/calculations.ts. */
  leverage: number;

  /** Price at which the position was opened. */
  entryPrice: number;
  /** Price at which the position was (or will be) closed. Undefined while open. */
  exitPrice?: number;
  /** Planned stop-loss price — defines the risk side of the RR ratio. */
  stopLoss?: number;
  /** Planned take-profit price — defines the reward side of the RR ratio. */
  takeProfit?: number;

  /** Any extra costs (commission, spread, swap) subtracted from PnL. */
  fees?: number;

  /** ISO date-time string for when the trade was opened. */
  entryDate: string;
  /** ISO date-time string for when the trade was closed. Undefined while open. */
  exitDate?: string;

  /** open | closed — derived mostly from whether exitPrice is set. */
  status: TradeStatus;

  /** Free-form notes: setup, thesis, mistakes, lessons learned. */
  notes?: string;
  /** Optional tags for filtering, e.g. ["breakout", "news", "revenge-trade"]. */
  tags?: string[];

  /** IDs of screenshots attached to this trade, stored in IndexedDB. */
  screenshotIds?: string[];

  /** Record bookkeeping. */
  createdAt: string;
  updatedAt: string;
}

/** Fields the user fills in via the trade form (id/userId/timestamps are
 *  generated by the app, not typed by hand). */
export type TradeFormValues = Omit<
  Trade,
  'id' | 'userId' | 'status' | 'createdAt' | 'updatedAt' | 'screenshotIds'
>;

/** Computed, derived metrics for a single trade (never stored — always
 *  recalculated from the raw Trade fields so they can't go stale). */
export interface TradeMetrics {
  /** Profit or loss in account currency. Negative = loss. */
  pnl: number;
  /** PnL expressed as a percentage of margin used (ROE) — i.e. return on
   *  the capital actually tied up, not on the full notional value. This is
   *  the figure leverage directly amplifies: the same $ PnL produces a
   *  bigger % at 20x than at 2x, because less capital was committed. */
  pnlPercent: number;
  /** Capital actually committed to open the position: (entryPrice *
   *  quantity) / leverage. Shown alongside pnlPercent for context. */
  marginUsed: number;
  /** Planned risk:reward ratio, e.g. 2 means "2:1" (reward is 2x the risk). */
  plannedRR?: number;
  /** Realized R-multiple: actual PnL divided by the amount that was risked. */
  realizedR?: number;
  /** True once the trade is closed and pnl > 0. */
  isWin: boolean;
}

/** Registered user account (auth is local-only — see context/AuthContext). */
export interface User {
  id: string;
  name: string;
  email: string;
  /** SHA-256 hash of the password — never store plain text, even locally. */
  passwordHash: string;
  createdAt: string;
}

/** Publicly-safe view of a user (no password hash) kept in auth state. */
export type PublicUser = Omit<User, 'passwordHash'>;

/** Filter criteria used by the Trades page and Analytics dashboard. */
export interface TradeFilters {
  /** Free-text search across symbol and notes. */
  search: string;
  /** Restrict to long/short, or 'all'. */
  positionType: PositionType | 'all';
  /** Restrict to open/closed, or 'all'. */
  status: TradeStatus | 'all';
  /** Restrict to winners/losers, or 'all' (only meaningful for closed trades). */
  outcome: 'win' | 'loss' | 'all';
  /** ISO date string — only trades on/after this date. Empty = no bound. */
  dateFrom: string;
  /** ISO date string — only trades on/before this date. Empty = no bound. */
  dateTo: string;
}

/** A day's aggregated performance, used by the calendar view. */
export interface DailyPnlSummary {
  /** YYYY-MM-DD */
  date: string;
  pnl: number;
  pnlPercent: number;
  tradeCount: number;
}

/** Aggregate stats shown on the Analytics dashboard. */
export interface AnalyticsSummary {
  totalTrades: number;
  closedTrades: number;
  openTrades: number;
  totalPnl: number;
  winRate: number;
  averageRR: number;
  profitFactor: number;
  bestTrade: Trade | null;
  worstTrade: Trade | null;
  averageWin: number;
  averageLoss: number;
}

/**
 * The user's chosen theme. 'system' means "follow the OS setting" and is
 * re-resolved live if the OS preference changes; 'light'/'dark' are explicit
 * overrides that stick until the user picks something else.
 */
export type ThemePreference = 'system' | 'light' | 'dark';
